In [10]:
# Import Dependencies
import pandas as pd
from pathlib import Path
from pymongo import MongoClient

In [11]:
# Read the data into a Pandas Dataframe
Affordable_Housing_Inventory_20240703_df = pd.read_csv(r'C:\Users\aspyn\affordable_housing\Affordable_Housing_Inventory_20240703.csv')

In [12]:
Affordable_Housing_Inventory_20240703_df["Council_District"].unique()

array(['1', '2', '3', '9', '7', '8', '5', '4', '10', '6', 'ETJ'],
      dtype=object)

In [13]:
Affordable_Housing_Inventory_20240703_df[~(Affordable_Housing_Inventory_20240703_df["Council_District"] == "ETJ")]

,Contract_ID,Project_ID,Project_Name,Ownership,Developer,Address,ZIP,Parcel_ID,Council_District,Unit_Type,...,GO_Bonds_2018,GO_Bonds_2022,CDBG,CIP_Funds,HOME,HTF,Project_Connect,City_Subsidy,Longitude,Latitude
0,2,3225,M Station,Foundation Communities Inc.,Foundation Communities Inc.,2906 E Martin Luther King Jr Boulevard,78722.0,0212130144,1,Multifamily,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2000000.0,-97.708414,30.282007
1,3,3226,Garden Terrace Expansion (aka Garden Terrace P...,Garden Terrace Housing Corporation,Foundation Communities Inc.,1015 W William Cannon Drive,78745.0,0418140412,2,Multifamily,...,0.0,NaN,0.0,0.0,0.0,500000.0,NaN,500000.0,-97.793427,30.198641
2,4,3227,LifeWorks Transitional Living Project,Lifeworks,Lifeworks,3710 S 2nd Street,78704.0,0407060308,3,Multifamily,...,0.0,NaN,0.0,0.0,0.0,300000.0,NaN,300000.0,-97.771020,30.229837
3,5,3228,Cornerstone,Mary Lee Community,Mary Lee Foundation,1322 Lamar Square Drive,78704.0,0102040407,9,Multifamily,...,0.0,NaN,0.0,0.0,1009502.0,0.0,NaN,0.0,-97.764224,30.255306
4,6,3229,The Willows,Mary Lee Community,Mary Lee Foundation,1330 Lamar Square Drive,78704.0,0102040412,9,Multifamily,...,0.0,NaN,0.0,0.0,0.0,0.0,NaN,2250000.0,-97.765039,30.254456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2318,958,6064,2901 E. 5th,Venky Cehllapa & Vijaya Venkatesh,Russell Architecture,2901 E. 5th St.,78702.0,0202120701,3,Multifamily,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-97.710090,30.255800
2319,959,6065,Loyola Flats,ECG Acquisitions LLC,ECG Acquisitions LLC,6700 Decker Ln.,78724.0,0217380521,1,Multifamily,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-97.628210,30.291970
2320,850,6066,The Lancaster Ownership,NaN,Capital A Housing,5107-5109 Lancater Ct.,78723.0,0221130303,4,Multifamily,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-97.705900,30.308060
2321,960,6067,Highland Studios,Foundation Communities Inc.,Foundation Communities Inc.,5900 & 5906 Airport Blvd.,78752.0,0226100304,4,Multifamily,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-97.715900,30.323680
2322,964,6071,1012 Concordia Ave.,1010 Concordia LP,1010 Concordia LP,1012 Concordia Ave.,78705.0,0215080826,9,Multifamily,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-97.721210,30.293190

In [14]:
Affordable_Housing_Inventory_20240703_df["Affordable_Units"].head()

0    140
1     15
2     12
3     30
4     64
Name: Affordable_Units, dtype: int64

In [15]:
x = Affordable_Housing_Inventory_20240703_df.groupby("Council_District")["Affordable_Units"].sum()

In [16]:
x.index

Index(['1', '10', '2', '3', '4', '5', '6', '7', '8', '9', 'ETJ'], dtype='object', name='Council_District')

In [17]:
x.astype(str)

Council_District
1      9237
10      602
2      7283
3      7233
4      5945
5      3736
6       730
7      3274
8       273
9      6128
ETJ     106
Name: Affordable_Units, dtype: object

In [18]:
district_totals = {}
for district in range(1, 11):  # Iterate through districts 1 to 10
    total_units = Affordable_Housing_Inventory_20240703_df[
        Affordable_Housing_Inventory_20240703_df["Council_District"] == str(district)
    ]["Affordable_Units"].sum()
    district_totals[f"Council District {district}"] = total_units

# Print the results
print("Total number of affordable units in each council district:")
for district, total_units in district_totals.items():
    print(f"{district}: {total_units}")

Total number of affordable units in each council district:
Council District 1: 9237
Council District 2: 7283
Council District 3: 7233
Council District 4: 5945
Council District 5: 3736
Council District 6: 730
Council District 7: 3274
Council District 8: 273
Council District 9: 6128
Council District 10: 602

In [5]:
# Example district_totals dictionary (replace with your actual data)
district_totals = {
    "Council District 1": 9237,
    "Council District 2": 7283,
    "Council District 3": 7233,
    "Council District 4": 5945,
    "Council District 5": 3736,
    "Council District 6": 730,
    "Council District 7": 3274,
    "Council District 8": 273,
    "Council District 9": 6128,
    "Council District 10": 602
}

# Calculate total number of affordable units across all districts
total_all_districts = sum(district_totals.values())

# Calculate total number of affordable units for Districts 6, 9, and 10
districts_to_include = ["Council District 6", "Council District 9", "Council District 10"]
total_districts_6_9_10 = sum(district_totals[district] for district in districts_to_include)

# Calculate percentage
if total_all_districts > 0:
    percentage_districts_6_9_10 = (total_districts_6_9_10 / total_all_districts) * 100
    print(f"Districts 6, 9, and 10 represent {percentage_districts_6_9_10:.2f}% of all districts.")
else:
    print("No data found.")

# Calculate percentage for Districts 1 to 4 and 7
districts_to_include_1_to_4_and_7 = ["Council District 1", "Council District 2", "Council District 3", "Council District 4", "Council District 7"]
total_districts_1_to_4_and_7 = sum(district_totals[district] for district in districts_to_include_1_to_4_and_7)

if total_all_districts > 0:
    percentage_districts_1_to_4_and_7 = (total_districts_1_to_4_and_7 / total_all_districts) * 100
    print(f"Districts 1 to 4 and 7 represent {percentage_districts_1_to_4_and_7:.2f}% of all districts.")
else:
    print("No data found.")

Districts 6, 9, and 10 represent 16.79% of all districts.
Districts 1 to 4 and 7 represent 74.19% of all districts.

In [19]:
district_coords = {}
for district in range(1, 11):  # Iterate through districts 1 to 10
    district_df = Affordable_Housing_Inventory_20240703_df[
        Affordable_Housing_Inventory_20240703_df["Council_District"] == str(district)
    ]
    lat = district_df["Latitude"].mean()  # Take the mean latitude for the district
    long = district_df["Longitude"].mean()  # Take the mean longitude for the district
    district_coords[f"Council District {district}"] = (lat, long)

# Print the results
print("Latitude and Longitude for each council district:")
for district, coords in district_coords.items():
    print(f"{district}: Lat={coords[0]:.6f}, Long={coords[1]:.6f}")

Latitude and Longitude for each council district:
Council District 1: Lat=30.288871, Long=-97.683747
Council District 2: Lat=30.172978, Long=-97.733335
Council District 3: Lat=30.248550, Long=-97.711570
Council District 4: Lat=30.330155, Long=-97.700422
Council District 5: Lat=30.176892, Long=-97.813620
Council District 6: Lat=30.449109, Long=-97.765563
Council District 7: Lat=30.376550, Long=-97.720055
Council District 8: Lat=30.240888, Long=-97.856039
Council District 9: Lat=30.291559, Long=-97.708933
Council District 10: Lat=30.329986, Long=-97.758131

In [20]:
# Calculate the total affordable units across all districts (Council District 1 to 10)
total_affordable_units = 0
for district in range(1, 11):  # Iterate through districts 1 to 10
    total_units = Affordable_Housing_Inventory_20240703_df[
        Affordable_Housing_Inventory_20240703_df["Council_District"] == str(district)
    ]["Affordable_Units"].sum()
    total_affordable_units += total_units

# Print the total number of affordable units across all districts
print(f"Total number of affordable units across all council districts: {total_affordable_units}")

Total number of affordable units across all council districts: 44441

In [21]:
Affordable_Housing_Inventory_20240703_df[Affordable_Housing_Inventory_20240703_df["Council_District"] == "1"]["Affordable_Units"].sum()

9237

In [22]:
Affordable_Housing_Inventory_20240703_df[Affordable_Housing_Inventory_20240703_df["Council_District"] == "2"]["Affordable_Units"].sum()

7283

In [23]:
# Group by ZIP code and sum the affordable units
units_by_zip = Affordable_Housing_Inventory_20240703_df.groupby('ZIP')['Affordable_Units'].sum()

# Print the total number of affordable units by ZIP code
print("Total number of affordable units by ZIP code:")
print(units_by_zip)

Total number of affordable units by ZIP code:
ZIP
7878.0        0
78474.0       2
78610.0     292
78613.0       0
78617.0    1107
78652.0     174
78653.0    1021
78659.0     310
78660.0     240
78667.0     240
78701.0    1053
78702.0    3391
78703.0       8
78704.0    2044
78705.0    2235
78717.0     269
78721.0    2519
78722.0     356
78723.0    4380
78724.0    1391
78725.0     236
78726.0     110
78727.0     433
78728.0     104
78729.0     190
78730.0     120
78731.0     395
78732.0       1
78735.0     218
78738.0       0
78741.0    2651
78744.0    4646
78745.0    2162
78746.0      93
78747.0     902
78748.0    1199
78749.0      52
78750.0     160
78751.0     805
78752.0    1450
78753.0    2716
78754.0    1626
78756.0     621
78757.0     342
78758.0    1638
78759.0     231
Name: Affordable_Units, dtype: int64

In [24]:
# Group by ZIP code and sum the affordable units
units_by_zip = Affordable_Housing_Inventory_20240703_df.groupby('ZIP')['Affordable_Units'].sum()

# Print the total number of affordable units by ZIP code
print("Total number of affordable units by ZIP code:")
print(units_by_zip)

Total number of affordable units by ZIP code:
ZIP
7878.0        0
78474.0       2
78610.0     292
78613.0       0
78617.0    1107
78652.0     174
78653.0    1021
78659.0     310
78660.0     240
78667.0     240
78701.0    1053
78702.0    3391
78703.0       8
78704.0    2044
78705.0    2235
78717.0     269
78721.0    2519
78722.0     356
78723.0    4380
78724.0    1391
78725.0     236
78726.0     110
78727.0     433
78728.0     104
78729.0     190
78730.0     120
78731.0     395
78732.0       1
78735.0     218
78738.0       0
78741.0    2651
78744.0    4646
78745.0    2162
78746.0      93
78747.0     902
78748.0    1199
78749.0      52
78750.0     160
78751.0     805
78752.0    1450
78753.0    2716
78754.0    1626
78756.0     621
78757.0     342
78758.0    1638
78759.0     231
Name: Affordable_Units, dtype: int64

In [25]:
# Drop unwanted columns

columns_to_drop = ['PSH_Units', 'MFI_20', 'MFI_30', 'MFI_40', 'MFI_50', 
                   'MFI_60', 'MFI_65', 'MFI_70', 'MFI_80', 'MFI_100', 'MFI_120',
                   'FIL_Status', 'CAL_FIL', 'Date_FIL_Recorded', 'Dev_Agreement',
                   'Density_Bonus', 'FIL', 'LIHTC', 'GO_Bonds_2006', 'GO_Bonds_2013',
                   'GO_Bonds_2018', 'GO_Bonds_2022', 'CDBG', 'CIP_Funds', 'HOME',
                   'HTF', 'Project_Connect', 'City_Subsidy']

Affordable_Housing_Inventory_20240703_df.drop(columns=columns_to_drop, inplace=True)

# Print the head of the DataFrame to verify the columns are dropped
print(Affordable_Housing_Inventory_20240703_df.head())

   Contract_ID  Project_ID                                       Project_Name  \
0            2        3225                                          M Station
1            3        3226  Garden Terrace Expansion (aka Garden Terrace P...
2            4        3227              LifeWorks Transitional Living Project
3            5        3228                                        Cornerstone
4            6        3229                                        The Willows

                            Ownership                    Developer  \
0         Foundation Communities Inc.  Foundation Communities Inc.
1  Garden Terrace Housing Corporation  Foundation Communities Inc.
2                           Lifeworks                    Lifeworks
3                  Mary Lee Community          Mary Lee Foundation
4                  Mary Lee Community          Mary Lee Foundation

                                  Address      ZIP   Parcel_ID  \
0  2906 E Martin Luther King Jr Boulevard  78722.0  0212130144
1             1015 W William Cannon Drive  78745.0  0418140412
2                       3710 S 2nd Street  78704.0  0407060308
3                 1322 Lamar Square Drive  78704.0  0102040407
4                 1330 Lamar Square Drive  78704.0  0102040412

  Council_District    Unit_Type  ... Total_ADA_Units Affordability_Start_Date  \
0                1  Multifamily  ...             0.0               11-16-2009
1                2  Multifamily  ...             0.0               10-08-2007
2                3  Multifamily  ...             2.0               05-04-2006
3                9  Multifamily  ...             4.0               11-21-2002
4                9  Multifamily  ...             0.0               08-31-2010

   Affordability_Expiration_Date  Affordability_Period   HDA  \
0                     11-16-2108                  99.0  RHDA
1                     10-08-2037                  30.0  RHDA
2                     05-04-2026                  20.0  RHDA
3                     11-21-2022                  20.0  RHDA
4                     08-31-2050                  40.0  RHDA

  Private_Activity_Bonds Affordability_Unlocked  SMART  Longitude   Latitude
0                     No                     No    Yes -97.708414  30.282007
1                     No                     No    Yes -97.793427  30.198641
2                     No                     No    Yes -97.771020  30.229837
3                     No                     No    Yes -97.764224  30.255306
4                     No                     No    Yes -97.765039  30.254456

[5 rows x 24 columns]

In [26]:
Affordable_Housing_Inventory_20240703_df.head()

,Contract_ID,Project_ID,Project_Name,Ownership,Developer,Address,ZIP,Parcel_ID,Council_District,Unit_Type,...,Total_ADA_Units,Affordability_Start_Date,Affordability_Expiration_Date,Affordability_Period,HDA,Private_Activity_Bonds,Affordability_Unlocked,SMART,Longitude,Latitude
0,2,3225,M Station,Foundation Communities Inc.,Foundation Communities Inc.,2906 E Martin Luther King Jr Boulevard,78722.0,0212130144,1,Multifamily,...,0.0,11-16-2009,11-16-2108,99.0,RHDA,No,No,Yes,-97.708414,30.282007
1,3,3226,Garden Terrace Expansion (aka Garden Terrace P...,Garden Terrace Housing Corporation,Foundation Communities Inc.,1015 W William Cannon Drive,78745.0,0418140412,2,Multifamily,...,0.0,10-08-2007,10-08-2037,30.0,RHDA,No,No,Yes,-97.793427,30.198641
2,4,3227,LifeWorks Transitional Living Project,Lifeworks,Lifeworks,3710 S 2nd Street,78704.0,0407060308,3,Multifamily,...,2.0,05-04-2006,05-04-2026,20.0,RHDA,No,No,Yes,-97.771020,30.229837
3,5,3228,Cornerstone,Mary Lee Community,Mary Lee Foundation,1322 Lamar Square Drive,78704.0,0102040407,9,Multifamily,...,4.0,11-21-2002,11-21-2022,20.0,RHDA,No,No,Yes,-97.764224,30.255306
4,6,3229,The Willows,Mary Lee Community,Mary Lee Foundation,1330 Lamar Square Drive,78704.0,0102040412,9,Multifamily,...,0.0,08-31-2010,08-31-2050,40.0,RHDA,No,No,Yes,-97.765039,30.254456

In [27]:
# Import data into a Pandas DataFrame
Affordable_Housing_Inventory_20240703_df = pd.read_csv(r'C:\Users\aspyn\affordable_housing\Affordable_Housing_Inventory_20240703.csv')

# Drop unwanted columns
columns_to_drop = ['PSH_Units', 'MFI_20', 'MFI_30', 'MFI_40', 'MFI_50', 
                   'MFI_60', 'MFI_65', 'MFI_70', 'MFI_80', 'MFI_100', 'MFI_120',
                   'FIL_Status', 'CAL_FIL', 'Date_FIL_Recorded', 'Dev_Agreement',
                   'Density_Bonus', 'FIL', 'LIHTC', 'GO_Bonds_2006', 'GO_Bonds_2013',
                   'GO_Bonds_2018', 'GO_Bonds_2022', 'CDBG', 'CIP_Funds', 'HOME',
                   'HTF', 'Project_Connect', 'City_Subsidy']
Affordable_Housing_Inventory_20240703_df.drop(columns=columns_to_drop, inplace=True)

# Calculate the total number of affordable units across all districts (Council District 1 to 10)
total_affordable_units = 0
for district in range(1, 11):
    total_units = Affordable_Housing_Inventory_20240703_df[
        Affordable_Housing_Inventory_20240703_df["Council_District"] == str(district)
    ]["Affordable_Units"].sum()
    total_affordable_units += total_units

# Calculate the percentage of affordable units
total_units = len(Affordable_Housing_Inventory_20240703_df)
percentage_affordable = (total_affordable_units / total_units) * 100

# Convert total_affordable_units to Python int
total_affordable_units = int(total_affordable_units)

# Convert DataFrame to a list of dictionaries
data_to_insert = Affordable_Housing_Inventory_20240703_df.to_dict(orient='records')

# Connect to MongoDB
client = MongoClient('localhost', 27017)
db = client['mydatabase']

# Collection for affordable housing details
collection_affordable_housing = db['affordable_housing']
result_affordable_housing = collection_affordable_housing.insert_many(data_to_insert)
print(f"Inserted {len(result_affordable_housing.inserted_ids)} documents into 'affordable_housing' collection")

# Collection for statistics or aggregated data
statistics_data = {
    'total_units': total_units,
    'total_affordable_units': total_affordable_units,
    'percentage_affordable': percentage_affordable
}

collection_statistics = db['housing_statistics']
result_statistics = collection_statistics.insert_one(statistics_data)
print(f"Inserted document into 'housing_statistics' collection")

# Close MongoDB connection
client.close()

Inserted 2323 documents into 'affordable_housing' collection
Inserted document into 'housing_statistics' collection